language: python
install:
  - pip install tox
dist: xenial
python: 3.5
script:
    - tox -e $TOX_ENV
matrix:
  include:
    # TEST DOCS AND LINTING
    - env: TOX_ENV=py3-docs
    - env: TOX_ENV=py3-lint

    # UNIT TESTS
    # On most recent versions of python.
    #
    - env: TOX_ENV=py35
      after_install:
        - pip install codacy-coverage
        - pip install codecov
      after_success:
        # Correct coverage xml for coverage services.
        - >
          bash -c 'set -eux;
          pkg_path=$(find .tox/py*/lib/python*/site-packages/pytest_workflow -maxdepth 0 -type d);
          sed -i "s:${pkg_path}:src/pytest_workflow:g" coverage.xml'
        - >
          bash -c ' if [[ -v CODACY_PROJECT_TOKEN ]]; then
          python-codacy-coverage -r coverage.xml;
          fi'
        - codecov
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.7
      env: TOX_ENV=py37

    # FUNCTIONAL TESTS
    - env: TOX_ENV=py3-snakemake
    - python: 3.6
      env: TOX_ENV=py3-snakemake
    - env: TOX_ENV=py3-cromwell
      before_install:
        # Install conda
        - export MINICONDA=${HOME}/miniconda
        - export PATH=${MINICONDA}/bin:${PATH}
        - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -f -p ${MINICONDA}
        - conda config --set always_yes yes
        - conda config --add channels defaults
        - conda config --add channels bioconda
        - conda config --add channels conda-forge
        - conda env create -n my_env cromwell
        - source activate my_env
