language: python
install:
  - pip install tox
  - pip install codacy-coverage
  - pip install codecov
matrix:
  include:
    # Test most recent editions of python 3
    - python: 3.5
      env: TOX_ENV=py35
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.7
      dist: xenial
      env: TOX_ENV=py37
script:
    - tox -e $TOX_ENV

after_success:
  # Only run if CODACY_PROJECT_TOKEN is defined.
    # This is not the case for pull requests outside of LUMC/pytest_workflow
    - >
      bash -c 'set -eux; if [[ -v CODACY_PROJECT_TOKEN ]]; then
        pkg_path=$(find .tox/py*/lib/python*/site-packages/pytest_workflow -maxdepth 0 -type d);
        sed -i "s:${pkg_path}:src/pytest_workflow:g" coverage.xml;
        python-codacy-coverage -r coverage.xml;
      fi'
      
    - >
      bash -c 'set -eux; if [[ -v CODECOV_TOKEN ]] ; then
      pkg_path=$(find .tox/py*/lib/python*/site-packages/pytest_workflow -maxdepth 0 -type d);
      sed -i "s:${pkg_path}:src/pytest_workflow:g" coverage.xml;
      codecov ;
      fi'