language: python
install:
  - pip install tox
matrix:
  include:
    # Test most recent editions of python 3
    - python: 3.5
      dist: xenial
      after_install:
        - pip install codacy-coverage
        - pip install codecov
      env: TOX_ENV=py35
      after_success:
        # Correct coverage xml for coverage services.
        - >
          bash -c 'set -eux;
          pkg_path=$(find .tox/py*/lib/python*/site-packages/pytest_workflow -maxdepth 0 -type d);
          sed -i "s:${pkg_path}:src/pytest_workflow:g" coverage.xml'
        - >
          bash -c ' if [[ -v CODACY_PROJECT_TOKEN ]]; then
          python-codacy-coverage -r coverage.xml;
          fi'
        - codecov
    - python: 3.6
      dist: xenial
      env: TOX_ENV=py36
    - python: 3.7
      dist: xenial
      env: TOX_ENV=py37
    - python: 3.5
      dist: xenial
      env: TOX_ENV=py3-docs
    - python: 3.5
      dist: xenial
      env: TOX_ENV=py3-snakemake
    - python: 3.6
      dist: xenial
      env: TOX_ENV=py3-snakemake
script:
    - tox -e $TOX_ENV

